import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      
      home: Scaffold(
        
        body: ListView(children: [
          Feed(),
        ]),
      ),
      debugShowCheckedModeBanner: false
    );
  }
}

class Feed extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 640,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFF333333)),
          child: Stack(
            children: [
              Positioned(
                left: 19,
                top: 514,
                child: Container(
                  width: 186,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 186,
                        height: 30,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    height: 22,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 22,
                                            height: 22,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFD9D9D9),
                                              shape: OvalBorder(),
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 25,
                                          top: 3.50,
                                          child: SizedBox(
                                            width: 75,
                                            height: 16,
                                            child: Text(
                                              'USERNAME',
                                              style: TextStyle(
                                                color: Colors.white,
                                                fontSize: 10,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 0.16,
                                                letterSpacing: -0.10,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  Container(
                                    width: 63.46,
                                    height: 15,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 0,
                                          child: Container(
                                            width: 63.46,
                                            height: 15,
                                            decoration: ShapeDecoration(
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(
                                                  width: 0.50,
                                                  strokeAlign: BorderSide.strokeAlignOutside,
                                                  color: Colors.white,
                                                ),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                            ),
                                          ),
                                        ),
                                        Positioned(
                                          left: 5.20,
                                          top: 0.47,
                                          child: SizedBox(
                                            width: 53.06,
                                            height: 14.06,
                                            child: Text(
                                              'Follow',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Colors.white,
                                                fontSize: 8,
                                                fontFamily: 'Inter',
                                                fontWeight: FontWeight.w400,
                                                height: 0.25,
                                                letterSpacing: -0.08,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            SizedBox(
                              width: 166,
                              height: 27,
                              child: Text(
                                'description',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 10,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0.16,
                                  letterSpacing: -0.10,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 15),
                      Container(
                        width: 14,
                        height: 14,
                        padding: const EdgeInsets.only(
                          top: 1.17,
                          left: 1.17,
                          right: 1.75,
                          bottom: 0.83,
                        ),
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                          
                          ],
                        ),
                      ),
                      const SizedBox(width: 15),
                      SizedBox(
                        width: 76,
                        height: 11,
                        child: Text(
                          'Original Sound',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 10,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w400,
                            height: 0,
                            letterSpacing: 0.20,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 298,
                top: 300,
                child: Container(
                  width: 61,
                  height: 273,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: double.infinity,
                        height: 38,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 28,
                              height: 28,
                              padding: const EdgeInsets.symmetric(vertical: 1.17),
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                
                                ],
                              ),
                            ),
                            const SizedBox(height: 2),
                            SizedBox(
                              width: 60,
                              height: 14,
                              child: Text(
                                '100.0K',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 13,
                                  fontFamily: 'Inter',
                                  fontWeight: FontWeight.w400,
                                  height: 0.09,
                                  letterSpacing: -0.13,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16),
                      Container(
                        width: 60,
                        height: 48,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 49,
                              top: 0,
                            
                                child: Container(
                                  width: 36,
                                  height: 36,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: FlutterLogo(),
                                ),
                              ),
                            
                            Positioned(
                              left: 0,
                              top: 34,
                              child: SizedBox(
                                width: 60,
                                height: 14,
                                child: Text(
                                  '10.0K',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 13,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.13,
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16),
                      Container(
                        width: 60,
                        height: 42,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 28,
                              child: SizedBox(
                                width: 60,
                                height: 14,
                                child: Text(
                                  '10.0K',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 13,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.13,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 11,
                              top: 0,
                              child: Container(
                                width: 38,
                                height: 30,
                                padding: const EdgeInsets.only(
                                  top: 2.66,
                                  left: 7.92,
                                  right: 7.92,
                                  bottom: 2.50,
                                ),
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                  
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16),
                      Container(
                        height: 45,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 31,
                              child: SizedBox(
                                width: 60,
                                height: 14,
                                child: Text(
                                  '1.9K',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 13,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.13,
                                  ),
                                ),
                              ),
                            ),
                            Positioned(
                              left: 48,
                              top: 0,
                        
                                child: Container(
                                  width: 33,
                                  height: 31,
                                  padding: const EdgeInsets.only(
                                    top: 3.34,
                                    left: 3.46,
                                    right: 2.75,
                                    bottom: 7.58,
                                  ),
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                    
                                    ],
                                  ),
                                ),
                              ),
                            
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 14,
                top: 5,
                child: Container(
                  height: 24,
                  padding: const EdgeInsets.symmetric(vertical: 2.65),
                  decoration: BoxDecoration(color: Color(0x00534141)),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 300,
                        height: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Expanded(
                              child: Container(
                                height: double.infinity,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      height: 17,
                                      child: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        mainAxisAlignment: MainAxisAlignment.start,
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          Container(
                                            width: 80,
                                            height: 17,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFA99BFF),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 1, color: Color(0xFFF5F5F5)),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                            ),
                                          ),
                                          const SizedBox(width: 20),
                                          Container(
                                            width: 80,
                                            height: 17,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFA99BFF),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 1, color: Color(0xFFF5F5F5)),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                            ),
                                          ),
                                          const SizedBox(width: 20),
                                          Container(
                                            width: 80,
                                            height: 17,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFA99BFF),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 1, color: Color(0xFFF5F5F5)),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                            ),
                                          ),
                                          const SizedBox(width: 20),
                                          Container(
                                            width: 80,
                                            height: 17,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFA99BFF),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 1, color: Color(0xFFF5F5F5)),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                            ),
                                          ),
                                          const SizedBox(width: 20),
                                          Container(
                                            width: 80,
                                            height: 17,
                                            decoration: ShapeDecoration(
                                              color: Color(0xFFA99BFF),
                                              shape: RoundedRectangleBorder(
                                                side: BorderSide(width: 1, color: Color(0xFFF5F5F5)),
                                                borderRadius: BorderRadius.circular(12),
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 11),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 594,
                child: Container(
                  width: 360,
                  height: 48.98,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.symmetric(horizontal: 15),
                        decoration: ShapeDecoration(
                          color: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(10),
                              topRight: Radius.circular(10),
                            ),
                          ),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 330,
                              height: 43,
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 27,
                                    height: 35,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 24,
                                          padding: const EdgeInsets.only(
                                            top: 1.99,
                                            left: 1.99,
                                            right: 2,
                                            bottom: 2,
                                          ),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                            
                                            ],
                                          ),
                                        ),
                                        SizedBox(
                                          width: double.infinity,
                                          height: 7,
                                          child: Text(
                                            'Home',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Color(0xFFA99BFF),
                                              fontSize: 7,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0.33,
                                              letterSpacing: -0.21,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 40),
                                  Container(
                                    width: 42,
                                    height: 35,
                                    padding: const EdgeInsets.symmetric(horizontal: 2),
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        SizedBox(
                                          width: double.infinity,
                                          height: 7,
                                          child: Text(
                                            'My Courses',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 7,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0.33,
                                              letterSpacing: -0.21,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 40),
                                  Container(
                                    width: 38,
                                    height: 35,
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                      
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 40),
                                  Container(
                                    width: 40,
                                    height: 35,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 21.16,
                                          height: 23,
                                          child: Stack(),
                                        ),
                                        SizedBox(
                                          width: double.infinity,
                                          height: 6,
                                          child: Text(
                                            'Inbox',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 7,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0.33,
                                              letterSpacing: -0.21,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                  const SizedBox(width: 40),
                                  Container(
                                    width: 24,
                                    height: 38.89,
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 23.33,
                                          padding: const EdgeInsets.only(
                                            top: 1.94,
                                            left: 3,
                                            right: 3,
                                            bottom: 2.92,
                                          ),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                            
                                            ],
                                          ),
                                        ),
                                        SizedBox(
                                          width: double.infinity,
                                          height: 15.56,
                                          child: Text(
                                            'Profile',
                                            style: TextStyle(
                                              color: Colors.black,
                                              fontSize: 7,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0.33,
                                              letterSpacing: -0.21,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}